server:
      port=3000
management:
   security:
      enabled: false  
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
spring:
   application:
      name: spring-boot-microservices-example       